export const child_birth = [
  'pregnant',
  'vaginal birth',
  'impregnation',
  'breast feeding',
  'milking',
  'lactation',
]

export const innocent = [
  'living clothes',
  'nudism',
  'petrification',
  'forced exposure',
  'nudity only',
  'hidden sex',
  'exhibitionism',
  'tickling',

  'virginity',
  'defloration',
  'real doll',
  'oil',
  'exposed clothing',
]

export const hardcode = [
  'ponygirl',
  'tube',
  'wooden horse',
  'vacbed',
  'gasmask',
  'human cattle',
  'speculum',
  'property tag',
  'table masturbation',
  'object insertion only',
  'hardcore',
  'haigure',
  'navel birth',
  'confinement',
  'straitjacket',
  'pillory',
  'electric shocks',
  'unusual insertions',
  'forniphilia',
  'coprophagia',
  'omorashi',
  'humiliation',
  'asphyxiation',
  'clamp',
  'orgasm denial',
  'blind',
  'genital piercing',
  'stomach deformation',
  'bdsm',
  'butt plug',
  'all the way through',
  'amputee',
  'stretching',
  'whip',
  'petplay',

  'pegging',
  'mind break',
  'nipple stimulation',
  'mind control',
  'blood',
  'anal birth',
  'invisible',
  'sex toys',
  'masked face',
  'eyemask',
  'double anal',
  'shibari',
  'time stop',
  'ruined orgasm',
  'moral degeneration',
  'ass expansion',
  'bondage',

  'vomit',
  'anal prolapse',
  'femdom',
  'high heels',
  'strap-on',
  'prostitution',
  'triple anal',
  'piercing',
  'nose fuck',
  'nose hook',
  'brain fuck',
  'chikan',
  'gag',
  'underwater sex',
  'stuck in wall',
  'public use',
  'piss drinking',
  'headless',
  'leash',
  'machine',
  'inflation',
  'internal urination',
  'large insertions',
  'latex',
  'gaping',
  'gloves',
  'gokkun',
  'chastity belt',
  'collar',
  'domination loss',
  'blindfold',
  'cervix prolapse',
  'chloroform',
  'prolapse',
  'double penetration',
  'tail plug',
  'eggs',
  'nipple expansion',
  'nipple fuck',
  'nipple piercing',
  'smell',
  'slave',
  'urethra insertion',
  'urination',
  'spanking',
  'torture',
  'blackmail',

  'yukkuri',
  'navel fuck',
  'harness',
  'enema',
  'eye penetration',
  'scat insertion',
  'ear fuck',
  'syringe',
  'fanny packing',
]

export const decoration = [
  'depth grading',
  'food on body',
  'body painting',

  'transparent clothing',
  'vaginal sticker',
  'wet clothes',
  'bandaid',
  'bandages',
  'pasties',
  'diaper',
  'metal armor',
  'bodysuit',
  'body writing',
  'leotard',
  'bloomers',
  'corset',
  'crotch tattoo',
]

export const change = [
  'shared senses',

  'age progression',
  'gender change',
  'selfcest',
  'shapening',
  'full tour',
  'possession',
  'crossdressing',
  'skinsuit',
  'tomboy',
  'tomgirl',
  'transformation',
  'onahole',
  'clone',
  'personality excretion',
  'age regression',
  'animegao',
  'josou seme',
  'breast expansion',
  'breast reduction',
  'gender morph',
  'body modification',
  'feminization',
  'body swap',
  'doll joints',
  'otokofutanari',
  'wormhole',
  'dismantling',
]

export const age = [
  'lolicon',
  'shotacon',
  'low lolicon',
  'low shotacon',
  'toddlercon',
  'schoolgirl uniform',
  'kodomo doushi',
  'infantilism',
  'kindergarten uniform',
  'school gym uniform',
  'small breasts',
  'school swimsuit',
  'kigurumi pajama',
  'schoolboy uniform',
  'kodomo only',
]
