export default [
  'mecha boy',
  'mecha girl',
  'kangaroo boy',
  'kangaroo girl',
  'monkey boy',
  'monkey girl',
  'moth boy',
  'moth girl',
  'snail girl',
  'monster girl',
  'mouse boy',
  'rhinoceros girl',
  'tailjob',
  'mouse girl',
  'pig girl',
  'pig man',
  'otter boy',
  'otter girl',
  'panda boy',
  'panda girl',
  'lizard girl',
  'lizard guy',
  'demon girl',
  'alien',
  'alien girl',
  'cowgirl',
  'cowman',
  'angel',
  'bat boy',
  'bat girl',
  'bear boy',
  'bear girl',
  'bee boy',
  'bee girl',
  'bunny boy',
  'bunny girl',
  'bird boy',
  'bird girl',
  'catboy',
  'catgirl',
  'deer boy',
  'deer girl',
  'dog boy',
  'dog girl',
  'elephant boy',
  'elephant girl',
  'fox boy',
  'fox girl',
  'frog boy',
  'frog girl',
  'giraffe boy',
  'giraffe girl',
  'hedgehog boy',
  'hedgehog girl',
  'horse boy',
  'horse girl',
  'hyena boy',
  'hyena girl',
  'insect boy',
  'insect girl',
  'plant boy',
  'plant girl',
  'raccoon boy',
  'raccoon girl',
  'rhinoceros boy',
  'shark boy',
  'shark girl',
  'sheep boy',
  'sheep girl',
  'additional eyes',
  'adventitious mouth',
  'adventitious penis',
  'adventitious vagina',
  'vampire',
  'split tongue',
  'retractable penis',
  'orc',
  'bite mark',
  'conjoined',
  'midget',
  'multiple arms',
  'multiple breasts',
  'multiple nipples',
  'multiple tails',
  'multiple vaginas',
  'ghost',
  'skunk boy',
  'skunk girl',
  'slime boy',
  'elf',
  'zombie',
  'fairy',
  'halo',
  'horns',
  'mermaid',
  'merman',
  'tail',
  'kemonomimi',
  'wingjob',
  'wings',
  'witch',
  'demon',
  'long tongue',
  'slime girl',
  'monoeye',
  'oni',
  'monster',
  'robot',
  'slime',
  'skeleton',
  'snake boy',
  'snake girl',
  'spider boy',
  'spider girl',
  'squid boy',
  'squid girl',
  'squirrel boy',
  'squirrel girl',
  'wolf boy',
  'wolf girl',
]
